
ALTER TABLE public.objetivos
  ADD COLUMN IF NOT EXISTS meta_roas NUMERIC,
  ADD COLUMN IF NOT EXISTS presupuesto_mensual NUMERIC,
  ADD COLUMN IF NOT EXISTS presupuesto_invertido NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS resultado_venta NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cantidad_lives INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS horas_lives NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'ventas',
  ADD COLUMN IF NOT EXISTS comentarios_bien TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS comentarios_mal TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS tareas_prioritarias TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS data_source TEXT;
